name: Build
on: [push]
jobs:
    windows_build:
        name: Windows build
        runs-on: windows-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v1
            - name: Checkout submodules
              run: git submodule update --init --recursive
            - name: Cache vcpkg
              uses: actions/cache@v1
              with:
                path: vcpkg
                key: ${{ runner.os }}-vcpkg-${{ hashFiles('build.windows') }}
            - name: vcpkg
              run: |
                if(!(Test-Path .\vcpkg))
                {
                git clone https://github.com/microsoft/vcpkg.git
                cd vcpkg
                echo "set(VCPKG_BUILD_TYPE release)" >> triplets/x64-windows.cmake
                .\bootstrap-vcpkg.bat
                .\vcpkg.exe integrate install
                .\vcpkg.exe install '@${{ github.workspace }}/build.windows'
                }
            - name: cmake
              run: cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake -G "Visual Studio 16 2019" -A x64 .
            - name: Setup MSBuild.exe
              uses: warrenbuckley/Setup-MSBuild@v1
            - name: MSBuild
              run: msbuild USC.sln -p:Configuration=Release /m /verbosity:minimal
            - name: Tests
              run: rm ./bin/Tests.*
            - name: Upload artifact
              uses: actions/upload-artifact@master
              with:
                name: Game
                path: bin
            - name: Trigger artifact distribution
              continue-on-error: true
              run: |
                Invoke-RestMethod -Method POST -ContentType "application/json" -Body '{ "id": ${{ github.run_id }}, "branch": "${{github.ref}}", "commit": "${{github.sha}}" }' -Uri ${{ secrets.WEBHOOK_URL }}
    linux_build:
        name: Linux build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v1
            - name: Checkout submodules
              run: git submodule update --init --recursive
            - name: Install packages
              run: |
                sudo apt-get update
                sudo apt-get install g++ libegl1-mesa-dev libfreetype6-dev libogg-dev libvorbis-dev libsdl2-dev libarchive-dev zlib1g-dev libjpeg-dev libpng-dev
            - name: cmake
              run: cmake -DCMAKE_BUILD_TYPE=Release .
            - name: make
              run: make
            - name: Prepare for bundling AppImage
              run: |
                sudo apt-get install appstream
                wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
                chmod +x linuxdeploy-x86_64.AppImage
            - name: Bundle AppImage
              run: |
                ./linuxdeploy-x86_64.AppImage --custom-apprun appimage/AppRun -d appimage/usc-game.desktop -i appimage/usc-game.png -e bin/usc-game --appdir usc-appdir --output appimage
                mv usc-game*.AppImage bin/usc-game.AppImage
                rm bin/usc-game bin/Tests.*
            - name: Upload artifact
              uses: actions/upload-artifact@master
              with:
                name: Game_linux_AppImage
                path: bin
    macos_build:
        name: macOS build
        runs-on: macos-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v1
            - name: Checkout submodules
              run: git submodule update --init --recursive
            - name: Install packages
              run: brew install cmake freetype libvorbis sdl2 libpng jpeg libarchive
            - name: cmake
              run: cmake . -DLibArchive_LIBRARY=/usr/local/opt/libarchive/lib/libarchive.dylib -DLibArchive_INCLUDE_DIR=/usr/local/opt/libarchive/include -DCMAKE_BUILD_TYPE=Release
            - name: make
              run: make
